name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check creds
      run: echo ${{ secrets.DOCKER_USERNAME }}
    - name: Login Dockerhub
      env:
       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Build the Docker image
      run: docker build -t cicd-pipeline:latest .
    - name: Push to Dockerhub
      run: docker push akib6074/cicd-pipeline:latest
